# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vit-pytorch',
                'doc_host': 'https://thatgeeman.github.io',
                'git_url': 'https://github.com/thatgeeman/vit-pytorch',
                'lib_path': 'vit_pytorch'},
  'syms': { 'vit_pytorch.core': {'vit_pytorch.core.foo': ('patch.html#foo', 'vit_pytorch/core.py')},
            'vit_pytorch.patch': { 'vit_pytorch.patch.PatchEmbedding': ('patch.html#patchembedding', 'vit_pytorch/patch.py'),
                                   'vit_pytorch.patch.PatchEmbedding.__init__': ( 'patch.html#patchembedding.__init__',
                                                                                  'vit_pytorch/patch.py'),
                                   'vit_pytorch.patch.PatchEmbedding.forward': ( 'patch.html#patchembedding.forward',
                                                                                 'vit_pytorch/patch.py')}}}
